### ISSUE TITLE
How to install this bubble screen saver on deepin and use it via deepin-screensaver ?

### ISSUE THREAD

**Issue by aiamuzz** [zccrs/screensaver-pp#1]
Its in chinese ... so can't claim i understand it fully ...

but can we install this bubble screen saver on deepin and use it via deepin-screensaver ?

Can we have an english readme-file ?

**Comment by holzboa** [comment]
It's available in pacman
`sudo pacman -S deepin-screensaver-pp` 
or you can get the `screensaver-pp_0.0.1_amd64.deb` here : https://mirror.deepines.com/deepin/pool/non-free/s/screensaver-pp/

**Comment by zccrs** [comment]
Hi, the screen saver is available in deepin V20.5 now, install it via following command:
````bash
sudo apt install github.zccrs.screensaver-pp
````
