### ISSUE TITLE
求问：怎样在manjaro中使用这款屏保

### ISSUE THREAD

**Issue by marsvet** [zccrs/screensaver-pp#2]
求问作者大大，怎样在manjaro中使用这款屏保，刚从deepin转到manjaro，deepin中可以直接设置屏保，manjaro好像没有设置屏保的功能。

**Comment by zccrs** [comment]
不好意思，没想到这个项目有人在关注。这款屏保现在没有支持 xscreensaver 的启动方式，如果是在 Manjaro 中用 DDE，那自己编译一个也能使用。
